### ISSUE TITLE
`read-data-subset` in documentation, but not accepted

### ISSUE THREAD

**Issue by duracell** [rustic-rs/docs#82]
In `check.md` is the `read-data-subset` argument explained, but this argument seems not available in the rustic binary.
Also in the comparison between restic and rustic it's mentioned that rustic does not have this feature.
So should this be deleted from the documentation?

**Comment by aawsome** [comment]
Thanks @duracell for opening this issue.
Actually this is wrong in the docu. However, there is https://github.com/rustic-rs/rustic_core/pull/262 which will add exactly that functionality soon to rustic...

**Comment by duracell** [comment]
That's great! Then it only needs to be checked if the documentation is correct this new function.
Also, the comparison table should be changed if it's available in the release.
I would let this issue open as reminder if this is fine for you? :)

**Comment by aawsome** [comment]
Letting this issue open until it's fixed in rustic is a good idea! Actually, it won't be the upcoming release 0.8.1 which is just a small bug-fix-release, but it will be in 0.9.0.

Actually, in 0.9.0 there will much finer selection of packs-to-read (and trees to check) available: There it will be possible to specify snapshot(s) whose needed packfiles are checked (or partly checked if combined with `read-data-subset`).

**Comment by simonsan** [comment]
rustic https://github.com/rustic-rs/rustic/releases/tag/v0.9.1 added this. Closing this. 🚀
